"""Atualizando Review

Revision ID: 85351f5e8b7e
Revises: 85498ff34b12
Create Date: 2025-08-23 10:57:28.055485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85351f5e8b7e'
down_revision = '85498ff34b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('book',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('published_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookshelf',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genre',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('count_followers', sa.Integer(), nullable=True),
    sa.Column('count_following', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('authors_book',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_book', sa.String(length=36), nullable=False),
    sa.Column('id_author', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('following',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id_follower', sa.String(length=36), nullable=False),
    sa.Column('id_followed', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_followed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_follower'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres_book',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_book', sa.String(length=36), nullable=False),
    sa.Column('id_genre', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_book',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_finish', sa.DateTime(), nullable=True),
    sa.Column('last_page', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('id_bookshelf', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_bookshelf'], ['bookshelf.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id_user_book', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_user_book'], ['user_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('id_user_book', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_user_book'], ['user_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('id_review', sa.String(length=36), nullable=True),
    sa.Column('id_note', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_note'], ['reading_progress.id'], ),
    sa.ForeignKeyConstraint(['id_review'], ['review.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked')
    op.drop_table('review')
    op.drop_table('reading_progress')
    op.drop_table('user_book')
    op.drop_table('genres_book')
    op.drop_table('following')
    op.drop_table('authors_book')
    op.drop_table('user')
    op.drop_table('genre')
    op.drop_table('bookshelf')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
